apiVersion: v1
kind: Service
metadata:
  name: graphwiz-alpha
spec:
  type: NodePort
  selector:
    run: graphwiz-alpha
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: backend
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: frontend

